version: '3.8'

services:
    nodejs:
        image: albertosola/nodejs
        volumes:
            - ./:/home/user/app
        ports:
            - '3000:3000'
        
        stdin_open: true
        tty: true